# Generated by Django 6.0.5 on 2026-05-15 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "monthly_credits",
                    models.PositiveIntegerField(
                        default=10000,
                        help_text="Free credits granted at the start of each billing cycle.",
                    ),
                ),
                (
                    "form_creation_cost",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Credits charged when a user creates a new form.",
                    ),
                ),
                (
                    "per_field_cost",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Credits charged per non-empty field in each submission payload.",
                    ),
                ),
                (
                    "per_email_cost",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Credits charged for every notification email sent.",
                    ),
                ),
                (
                    "reset_period_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Number of days between automatic free-credit refills (0 disables).",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserCreditBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("monthly_credits_used", models.PositiveIntegerField(default=0)),
                (
                    "last_reset_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="credits.creditplan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("form_creation", "Form creation"),
                            ("submission_fields", "Submission fields"),
                            ("email_sent", "Email sent"),
                            ("refill", "Monthly refill"),
                            ("admin_adjustment", "Admin adjustment"),
                            ("signup_bonus", "Signup bonus"),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="credits_cre_user_id_6943f8_idx",
                    ),
                    models.Index(
                        fields=["kind", "-created_at"],
                        name="credits_cre_kind_0a4e2f_idx",
                    ),
                ],
            },
        ),
    ]
