# Generated by Django 6.0.5 on 2026-05-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditplan",
            name="submit_rate_per_hour",
            field=models.PositiveIntegerField(
                default=1000,
                help_text="Max form submissions accepted per hour per access key (0 disables).",
            ),
        ),
        migrations.AddField(
            model_name="creditplan",
            name="submit_rate_per_minute",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Max form submissions accepted per minute per access key.",
            ),
        ),
    ]
