# Generated by Django 6.0.5 on 2026-05-15 17:59

import django.db.models.deletion
import misc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=120, unique=True)),
                ("value", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("bool", "Boolean"),
                            ("int", "Integer"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="If true, value is exposed to the dashboard UI.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="UIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to=misc.models.avatar_upload_to
                    ),
                ),
                (
                    "why_using",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("business_forms", "Business contact forms"),
                            ("feedback", "Customer feedback"),
                            ("lead_gen", "Lead generation"),
                            ("event", "Event / RSVP"),
                            ("surveys", "Surveys & research"),
                            ("personal", "Personal project"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "where_heard",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("search", "Search engine (Google, Bing, ...)"),
                            ("social", "Social media"),
                            ("friend", "Friend or colleague"),
                            ("blog", "Blog / article"),
                            ("youtube", "YouTube"),
                            ("github", "GitHub"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("individual", "Individual / Freelancer"),
                            ("startup", "Startup"),
                            ("smb", "Small / medium business"),
                            ("enterprise", "Enterprise"),
                            ("agency", "Agency"),
                            ("nonprofit", "Non-profit"),
                            ("education", "Education"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("survey_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misc_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
