# Generated by Django 6.0.5 on 2026-05-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company_business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "Individual / Freelancer"),
                    ("startup", "Startup"),
                    ("smb", "Small / medium business"),
                    ("enterprise", "Enterprise"),
                    ("agency", "Agency"),
                    ("nonprofit", "Non-profit"),
                    ("education", "Education"),
                    ("other", "Other"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(
                blank=True, default="", help_text="ISO 3166-1 alpha-2", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mobile_number",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pincode",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
