# Generated by Django 6.0.5 on 2026-05-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="data_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="submission",
            name="data_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
