# Generated by Django 6.0.5 on 2026-05-15 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_submission_data_deleted_submission_data_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="email_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used for this form's notification emails. Falls back to user default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forms",
                to="core.emailtemplate",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("form.created", "Form created"),
                            ("form.deleted", "Form deleted"),
                            ("form.toggled", "Form toggled"),
                            ("key.created", "Access key created"),
                            ("key.revoked", "Access key revoked"),
                            ("key.regenerated", "Access key regenerated"),
                            ("template.deleted", "Email template deleted"),
                            ("submission.purged", "Submission data purged"),
                            ("gmail.removed", "Gmail config removed"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable target reference (e.g. 'Form #4: Contact').",
                        max_length=200,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_auditl_user_id_969660_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_auditl_action_d80c2d_idx",
                    ),
                ],
            },
        ),
    ]
