# Generated by Django 6.0.5 on 2026-05-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_form_email_template_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="last_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("form.created", "Form created"),
                    ("form.deleted", "Form deleted"),
                    ("form.toggled", "Form toggled"),
                    ("key.created", "Access key created"),
                    ("key.revoked", "Access key revoked"),
                    ("key.regenerated", "Access key regenerated"),
                    ("template.deleted", "Email template deleted"),
                    ("submission.purged", "Submission data purged"),
                    ("gmail.removed", "Gmail config removed"),
                    ("email.retried", "Failed email retried"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("retrying", "Retrying"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
